### ISSUE TITLE
Ты жив?

### ISSUE THREAD

**Issue by UserSv4** [adasdead/ini#1]
Егор тебя потерял опять

**Comment by egor0044** [comment]
+++

**Comment by egor0044** [comment]
Если не вернёшься то из окна прыгну так что выбирай либо я либо ещё кто то или что то

**Comment by egor0044** [comment]
Мне кошмары про тебя снятся пожелей нас с юзером

**Comment by egor0044** [comment]
@adasdead Этот мальчик (@UserSv4 ) Обижает меня😭😭😭, помоги пожалуйста
